version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demopod
      POSTGRES_PASSWORD: "Zb_eRveEw_L-8gpENRE05HJNAXAKPYFB"
    volumes:
      - demopod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "KpkWIWiXdsrFy-P6t1FlUds_5Nkl4kz2"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  demopod_data:
